name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: docker://pandoc/core:2.9

    steps:
    - uses: actions/checkout@v2

    - name: Compile PDF
      run: make all
