name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Update apt
        run: sudo apt-get update

      - name: Install latex compiler
        run: sudo apt-get install -y texlive-xetex

      - name: Setup pandoc
        run: sudo apt-get install -y pandoc

      - name: Install font
        run: sudo apt-get install -y ttf-wqy-zenhei

      - name: Compile PDF
        run: make clean all

      - name: Commit PDF
        run: |
          git config --local user.email "peteryin1604@gmail.com"
          git config --local user.name "ptyin[bot]"
          git add -A pdf/
          git commit -m "Auto generating PDF"

      - name: Push to github
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
