name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install latex compiler
      run: sudo apt-get install -y texlive-latex-base

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Compile PDF
      run: make all
