name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Update apt
        run: sudo apt-get update

      - name: Install latex compiler
        run: sudo apt-get install -y texlive-xetex

      - name: Setup pandoc
        run: sudo apt-get install -y pandoc

      - name: Compile PDF
        run: make all
